akademia-web-dev/Homework3/WebDevHomework/Models/Link.cs
namespace WebDevHomework.Models
{
    public class Link
    {
        // Id used for creating hash for shortened link
        public int Id { get; set; }
        public string FullUrl { get; set; }
        public string ShortUrl { get; set; }
    }
}

akademia-web-dev/Homework3/WebDevHomework/Models/LinkResult.cs
using System.Collections.Generic;

namespace WebDevHomework.Models
{
    public class LinkResult
    {
        public IEnumerable<Link> Items { get; set; }
        public PageInfo PageInfo { get; set; }
    }

    public class PageInfo
    {
        public int CurrentPage { get; set; }

        public int MaxPage { get; set; }
    }
}

akademia-web-dev/Homework3/WebDevHomework/Controllers/LinkApiController.cs
using Microsoft.AspNetCore.Mvc;
using WebDevHomework.Interfaces;
using WebDevHomework.Models;

namespace WebDevHomework.Controllers
{
    [Route("api/Link")]
    public class LinkApiController : Controller
    {
        private readonly ILinkWriter _linkWriter;
        private readonly ILinkReader _linkReader;

        public LinkApiController(ILinkReader linkReader, ILinkWriter linkWriter)
        {
            _linkReader = linkReader;
            _linkWriter = linkWriter;
        }

        [HttpGet]
        public IActionResult Index(int? page = 1)
        {
            var result = _linkReader.GetLinks(page.Value);
            return Ok(result);
        }

        [HttpPost]
        public IActionResult Create(Link link)
        {
            _linkWriter.AddLink(link);
            return Ok(link);
        }

        [HttpDelete]
        public IActionResult Delete(int linkId)
        {
            _linkWriter.DeleteLink(linkId);
            return Ok();
        }
    }
}

akademia-web-dev/Homework3/WebDevHomework/Controllers/LinkController.cs
using Microsoft.AspNetCore.Mvc;
using WebDevHomework.Interfaces;
using WebDevHomework.Models;

namespace WebDevHomework.Controllers

{
    public class LinkController : Controller
    {
        private readonly ILinkWriter _linkWriter;
        private readonly ILinkReader _linkReader;

        public LinkController(ILinkReader linkReader, ILinkWriter linkWriter)
        {
            _linkReader = linkReader;
            _linkWriter = linkWriter;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var alllinks = _linkReader.GetLinks();
            return View(alllinks);
        }

        [HttpPost]
        public IActionResult Create(Link link)
        {
            _linkWriter.AddLink(link);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int linkId)
        {
            _linkWriter.DeleteLink(linkId);
            return RedirectToAction("Index");
        }
    }
}

akademia-web-dev/Homework3/WebDevHomework/Controllers/RedirectController.cs
using Microsoft.AspNetCore.Mvc;
using WebDevHomework.Interfaces;

namespace WebDevHomework.Controllers
{
    public class RedirectController : Controller
    {
        private readonly ILinkReader _linkReader;

        public RedirectController(ILinkReader linkReader)
        {
            _linkReader = linkReader;
        }

        [HttpGet("/{shortUrl}")]
        public IActionResult RedirectToUrl(string shortUrl)
        {
            var fullUrl = _linkReader.GetFullLink(shortUrl);
            return Redirect($"http://{fullUrl}");
        }
    }
}

akademia-web-dev/Homework3/WebDevHomework/Views/Link/Index.cshtml
@model List<WebDevHomework.Models.Link>
<div>
    <div>
        @using (Html.BeginForm("Create", "Link", FormMethod.Post))
        {
            <input type="text" name="FullUrl" placeholder="Full link"/> <br/>
            <button type="submit">Add</button>
        }
    </div>

    <div class="list">
        <table>
            @foreach(var item in Model) 
            {
                <tr>
                    <td>
                        <strong>Full link:</strong>
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.FullUrl)
                    </td>
                    <td>
                        <strong>Short link:</strong>
                    </td>
                    <td>
                        @Html.ActionLink(item.ShortUrl, "RedirectToUrl", "Redirect", new { shortUrl = item.ShortUrl }, new {target="_blank"})
                    </td>
                    <td>
                        | @Html.ActionLink("Delete", "Delete", "Link", new { linkId = item.Id })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>  