akademia-web-dev/Homework2/Models/ErrorViewModel.cs
using System;

namespace akademia_web_dev.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

akademia-web-dev/Homework2/Models/HyperLinkModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace akademia_web_dev.Models
{
    public class HyperLinkModel
    {
        public int Id { get; set; }
        public string Link { get; set; }
        public string Hash { get; set; }
    }
}

akademia-web-dev/Homework2/Controllers/HyperLinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using akademia_web_dev.Models;
using akademia_web_dev.Repositories;
using akademia_web_dev.Services;
using Microsoft.AspNetCore.Mvc;

namespace akademia_web_dev.Controllers
{
    public class HyperLinkController : Controller
    {

       // public static List<HyperLinkModel> _links = new List<HyperLinkModel>();
        private readonly ILinkRepository _repository;

        internal ILinkRepository Repository => _repository;

        [HttpGet]
        public IActionResult Index()
        {
            var links = _repository.Get(string.Empty, 0);
            return View(links);
        }

        [HttpPost]
        public IActionResult Create(HyperLinkModel link)
        {
            if (Regex.IsMatch(link.Link, @"[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)"))
            {
                
                _repository.Create(link);
                return RedirectToAction(nameof(Index));
            }
            return BadRequest("Niepoprawny link");
        }
    }
}

akademia-web-dev/Homework2/Controllers/RedirectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using akademia_web_dev.DB;
using akademia_web_dev.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace akademia_web_dev.Controllers
{
    public class RedirectController : Controller
    {
        private ILinkRepository _repository;
        private readonly LinkDBContext _context;


        [HttpGet]
        [Route("/link/{hash}")]
        public IActionResult Index(string hash)
        {
            var url = _context.link.Where(item => item.Hash == hash).FirstOrDefault();
            return Redirect(url.ToString());
        }
    }
}

akademia-web-dev/Homework2/Views/HyperLink/Index.cshtml
@model IEnumerable<akademia_web_dev.Models.HyperLinkModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @using (Html.BeginForm("Create", "HyperLink", FormMethod.Post))
        {
            <input type="text" name="link" placeholder="Enter your url here" />
            <input type="submit" value="OK!" />
        }
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Link)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        <a href="http://@item.Link">@item.Link</a>
                        <a href="/link/@item.Hash">@item.Hash</a>
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

akademia-web-dev/Homework2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - akademia_web_dev</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">akademia_web_dev</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - akademia_web_dev</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>